export const SAVE_SEARCH = "SAVE_SEARCH";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const LOADING = "LOADING";